// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zYgwBR3MYzAJ7FGcfRrYBDUPwvWLU-A',
    appId: '1:750723090094:web:3d27677e13bdc751854f3f',
    messagingSenderId: '750723090094',
    projectId: 'flutterapp0-e64b0',
    authDomain: 'flutterapp0-e64b0.firebaseapp.com',
    storageBucket: 'flutterapp0-e64b0.appspot.com',
    measurementId: 'G-XBEHZBXPH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvbNbZC7NX20ujifPrn2CIJu9SjsD2RZU',
    appId: '1:750723090094:android:01e49d9b4682cf40854f3f',
    messagingSenderId: '750723090094',
    projectId: 'flutterapp0-e64b0',
    storageBucket: 'flutterapp0-e64b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB8nGwQ0Rp0j9_cUgQPVyQEAV3hc5CJnk',
    appId: '1:750723090094:ios:71dd9a7cdfe19afd854f3f',
    messagingSenderId: '750723090094',
    projectId: 'flutterapp0-e64b0',
    storageBucket: 'flutterapp0-e64b0.appspot.com',
    iosClientId: '750723090094-md0o8ibbr2c16n5pao49ls51lt1vtrgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB8nGwQ0Rp0j9_cUgQPVyQEAV3hc5CJnk',
    appId: '1:750723090094:ios:dee216a795d854e8854f3f',
    messagingSenderId: '750723090094',
    projectId: 'flutterapp0-e64b0',
    storageBucket: 'flutterapp0-e64b0.appspot.com',
    iosClientId: '750723090094-2pmap0ajjcf98tiu05plr6urc405pnl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
